package com.example.iran.jsonsample;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;

public class QueryUtils {

    public static List<Repository> getRepositoryFromJson(){
        String json = JSON_DATA;
        List<Repository> lists = new ArrayList<>();


        try {
            JSONObject root = new JSONObject(json);
            JSONArray items = root.getJSONArray("items");

            for (int i =0 ; i< items.length();i++){

                JSONObject obj = items.getJSONObject(i);
                String name = obj.getString("name");

                Repository repository = new Repository(name);
                lists.add(repository);
            }


        } catch (JSONException e) {
            e.printStackTrace();
        }

    return lists;
    }

    private static String JSON_DATA = "{\n" +
            "  \"total_count\": 735606,\n" +
            "  \"incomplete_results\": false,\n" +
            "  \"items\": [\n" +
            "    {\n" +
            "      \"id\": 14098069,\n" +
            "      \"node_id\": \"MDEwOlJlcG9zaXRvcnkxNDA5ODA2OQ==\",\n" +
            "      \"name\": \"free-programming-books-zh_CN\",\n" +
            "      \"full_name\": \"justjavac/free-programming-books-zh_CN\",\n" +
            "      \"owner\": {\n" +
            "        \"login\": \"justjavac\",\n" +
            "        \"id\": 359395,\n" +
            "        \"node_id\": \"MDQ6VXNlcjM1OTM5NQ==\",\n" +
            "        \"avatar_url\": \"https://avatars1.githubusercontent.com/u/359395?v=4\",\n" +
            "        \"gravatar_id\": \"\",\n" +
            "        \"url\": \"https://api.github.com/users/justjavac\",\n" +
            "        \"html_url\": \"https://github.com/justjavac\",\n" +
            "        \"followers_url\": \"https://api.github.com/users/justjavac/followers\",\n" +
            "        \"following_url\": \"https://api.github.com/users/justjavac/following{/other_user}\",\n" +
            "        \"gists_url\": \"https://api.github.com/users/justjavac/gists{/gist_id}\",\n" +
            "        \"starred_url\": \"https://api.github.com/users/justjavac/starred{/owner}{/repo}\",\n" +
            "        \"subscriptions_url\": \"https://api.github.com/users/justjavac/subscriptions\",\n" +
            "        \"organizations_url\": \"https://api.github.com/users/justjavac/orgs\",\n" +
            "        \"repos_url\": \"https://api.github.com/users/justjavac/repos\",\n" +
            "        \"events_url\": \"https://api.github.com/users/justjavac/events{/privacy}\",\n" +
            "        \"received_events_url\": \"https://api.github.com/users/justjavac/received_events\",\n" +
            "        \"type\": \"User\",\n" +
            "        \"site_admin\": false\n" +
            "      },\n" +
            "      \"private\": false,\n" +
            "      \"html_url\": \"https://github.com/justjavac/free-programming-books-zh_CN\",\n" +
            "      \"description\": \":books: 免费的计算机编程类中文书籍，欢迎投稿\",\n" +
            "      \"fork\": false,\n" +
            "      \"url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN\",\n" +
            "      \"forks_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/forks\",\n" +
            "      \"keys_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/keys{/key_id}\",\n" +
            "      \"collaborators_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/collaborators{/collaborator}\",\n" +
            "      \"teams_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/teams\",\n" +
            "      \"hooks_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/hooks\",\n" +
            "      \"issue_events_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/issues/events{/number}\",\n" +
            "      \"events_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/events\",\n" +
            "      \"assignees_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/assignees{/user}\",\n" +
            "      \"branches_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/branches{/branch}\",\n" +
            "      \"tags_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/tags\",\n" +
            "      \"blobs_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/git/blobs{/sha}\",\n" +
            "      \"git_tags_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/git/tags{/sha}\",\n" +
            "      \"git_refs_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/git/refs{/sha}\",\n" +
            "      \"trees_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/git/trees{/sha}\",\n" +
            "      \"statuses_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/statuses/{sha}\",\n" +
            "      \"languages_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/languages\",\n" +
            "      \"stargazers_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/stargazers\",\n" +
            "      \"contributors_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/contributors\",\n" +
            "      \"subscribers_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/subscribers\",\n" +
            "      \"subscription_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/subscription\",\n" +
            "      \"commits_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/commits{/sha}\",\n" +
            "      \"git_commits_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/git/commits{/sha}\",\n" +
            "      \"comments_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/comments{/number}\",\n" +
            "      \"issue_comment_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/issues/comments{/number}\",\n" +
            "      \"contents_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/contents/{+path}\",\n" +
            "      \"compare_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/compare/{base}...{head}\",\n" +
            "      \"merges_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/merges\",\n" +
            "      \"archive_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/{archive_format}{/ref}\",\n" +
            "      \"downloads_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/downloads\",\n" +
            "      \"issues_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/issues{/number}\",\n" +
            "      \"pulls_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/pulls{/number}\",\n" +
            "      \"milestones_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/milestones{/number}\",\n" +
            "      \"notifications_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/notifications{?since,all,participating}\",\n" +
            "      \"labels_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/labels{/name}\",\n" +
            "      \"releases_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/releases{/id}\",\n" +
            "      \"deployments_url\": \"https://api.github.com/repos/justjavac/free-programming-books-zh_CN/deployments\",\n" +
            "      \"created_at\": \"2013-11-04T01:59:19Z\",\n" +
            "      \"updated_at\": \"2018-08-09T13:40:13Z\",\n" +
            "      \"pushed_at\": \"2018-07-13T10:50:25Z\",\n" +
            "      \"git_url\": \"git://github.com/justjavac/free-programming-books-zh_CN.git\",\n" +
            "      \"ssh_url\": \"git@github.com:justjavac/free-programming-books-zh_CN.git\",\n" +
            "      \"clone_url\": \"https://github.com/justjavac/free-programming-books-zh_CN.git\",\n" +
            "      \"svn_url\": \"https://github.com/justjavac/free-programming-books-zh_CN\",\n" +
            "      \"homepage\": \"http://weibo.com/justjavac\",\n" +
            "      \"size\": 825,\n" +
            "      \"stargazers_count\": 36955,\n" +
            "      \"watchers_count\": 36955,\n" +
            "      \"language\": \"JavaScript\",\n" +
            "      \"has_issues\": true,\n" +
            "      \"has_projects\": true,\n" +
            "      \"has_downloads\": true,\n" +
            "      \"has_wiki\": false,\n" +
            "      \"has_pages\": false,\n" +
            "      \"forks_count\": 12962,\n" +
            "      \"mirror_url\": null,\n" +
            "      \"archived\": false,\n" +
            "      \"open_issues_count\": 148,\n" +
            "      \"license\": {\n" +
            "        \"key\": \"gpl-3.0\",\n" +
            "        \"name\": \"GNU General Public License v3.0\",\n" +
            "        \"spdx_id\": \"GPL-3.0\",\n" +
            "        \"url\": \"https://api.github.com/licenses/gpl-3.0\",\n" +
            "        \"node_id\": \"MDc6TGljZW5zZTk=\"\n" +
            "      },\n" +
            "      \"forks\": 12962,\n" +
            "      \"open_issues\": 148,\n" +
            "      \"watchers\": 36955,\n" +
            "      \"default_branch\": \"master\",\n" +
            "      \"score\": 24.127882\n" +
            "    },\n" +
            "    {\n" +
            "      \"id\": 24953448,\n" +
            "      \"node_id\": \"MDEwOlJlcG9zaXRvcnkyNDk1MzQ0OA==\",\n" +
            "      \"name\": \"material-design-icons\",\n" +
            "      \"full_name\": \"google/material-design-icons\",\n" +
            "      \"owner\": {\n" +
            "        \"login\": \"google\",\n" +
            "        \"id\": 1342004,\n" +
            "        \"node_id\": \"MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=\",\n" +
            "        \"avatar_url\": \"https://avatars1.githubusercontent.com/u/1342004?v=4\",\n" +
            "        \"gravatar_id\": \"\",\n" +
            "        \"url\": \"https://api.github.com/users/google\",\n" +
            "        \"html_url\": \"https://github.com/google\",\n" +
            "        \"followers_url\": \"https://api.github.com/users/google/followers\",\n" +
            "        \"following_url\": \"https://api.github.com/users/google/following{/other_user}\",\n" +
            "        \"gists_url\": \"https://api.github.com/users/google/gists{/gist_id}\",\n" +
            "        \"starred_url\": \"https://api.github.com/users/google/starred{/owner}{/repo}\",\n" +
            "        \"subscriptions_url\": \"https://api.github.com/users/google/subscriptions\",\n" +
            "        \"organizations_url\": \"https://api.github.com/users/google/orgs\",\n" +
            "        \"repos_url\": \"https://api.github.com/users/google/repos\",\n" +
            "        \"events_url\": \"https://api.github.com/users/google/events{/privacy}\",\n" +
            "        \"received_events_url\": \"https://api.github.com/users/google/received_events\",\n" +
            "        \"type\": \"Organization\",\n" +
            "        \"site_admin\": false\n" +
            "      },\n" +
            "      \"private\": false,\n" +
            "      \"html_url\": \"https://github.com/google/material-design-icons\",\n" +
            "      \"description\": \"Material Design icons by Google\",\n" +
            "      \"fork\": false,\n" +
            "      \"url\": \"https://api.github.com/repos/google/material-design-icons\",\n" +
            "      \"forks_url\": \"https://api.github.com/repos/google/material-design-icons/forks\",\n" +
            "      \"keys_url\": \"https://api.github.com/repos/google/material-design-icons/keys{/key_id}\",\n" +
            "      \"collaborators_url\": \"https://api.github.com/repos/google/material-design-icons/collaborators{/collaborator}\",\n" +
            "      \"teams_url\": \"https://api.github.com/repos/google/material-design-icons/teams\",\n" +
            "      \"hooks_url\": \"https://api.github.com/repos/google/material-design-icons/hooks\",\n" +
            "      \"issue_events_url\": \"https://api.github.com/repos/google/material-design-icons/issues/events{/number}\",\n" +
            "      \"events_url\": \"https://api.github.com/repos/google/material-design-icons/events\",\n" +
            "      \"assignees_url\": \"https://api.github.com/repos/google/material-design-icons/assignees{/user}\",\n" +
            "      \"branches_url\": \"https://api.github.com/repos/google/material-design-icons/branches{/branch}\",\n" +
            "      \"tags_url\": \"https://api.github.com/repos/google/material-design-icons/tags\",\n" +
            "      \"blobs_url\": \"https://api.github.com/repos/google/material-design-icons/git/blobs{/sha}\",\n" +
            "      \"git_tags_url\": \"https://api.github.com/repos/google/material-design-icons/git/tags{/sha}\",\n" +
            "      \"git_refs_url\": \"https://api.github.com/repos/google/material-design-icons/git/refs{/sha}\",\n" +
            "      \"trees_url\": \"https://api.github.com/repos/google/material-design-icons/git/trees{/sha}\",\n" +
            "      \"statuses_url\": \"https://api.github.com/repos/google/material-design-icons/statuses/{sha}\",\n" +
            "      \"languages_url\": \"https://api.github.com/repos/google/material-design-icons/languages\",\n" +
            "      \"stargazers_url\": \"https://api.github.com/repos/google/material-design-icons/stargazers\",\n" +
            "      \"contributors_url\": \"https://api.github.com/repos/google/material-design-icons/contributors\",\n" +
            "      \"subscribers_url\": \"https://api.github.com/repos/google/material-design-icons/subscribers\",\n" +
            "      \"subscription_url\": \"https://api.github.com/repos/google/material-design-icons/subscription\",\n" +
            "      \"commits_url\": \"https://api.github.com/repos/google/material-design-icons/commits{/sha}\",\n" +
            "      \"git_commits_url\": \"https://api.github.com/repos/google/material-design-icons/git/commits{/sha}\",\n" +
            "      \"comments_url\": \"https://api.github.com/repos/google/material-design-icons/comments{/number}\",\n" +
            "      \"issue_comment_url\": \"https://api.github.com/repos/google/material-design-icons/issues/comments{/number}\",\n" +
            "      \"contents_url\": \"https://api.github.com/repos/google/material-design-icons/contents/{+path}\",\n" +
            "      \"compare_url\": \"https://api.github.com/repos/google/material-design-icons/compare/{base}...{head}\",\n" +
            "      \"merges_url\": \"https://api.github.com/repos/google/material-design-icons/merges\",\n" +
            "      \"archive_url\": \"https://api.github.com/repos/google/material-design-icons/{archive_format}{/ref}\",\n" +
            "      \"downloads_url\": \"https://api.github.com/repos/google/material-design-icons/downloads\",\n" +
            "      \"issues_url\": \"https://api.github.com/repos/google/material-design-icons/issues{/number}\",\n" +
            "      \"pulls_url\": \"https://api.github.com/repos/google/material-design-icons/pulls{/number}\",\n" +
            "      \"milestones_url\": \"https://api.github.com/repos/google/material-design-icons/milestones{/number}\",\n" +
            "      \"notifications_url\": \"https://api.github.com/repos/google/material-design-icons/notifications{?since,all,participating}\",\n" +
            "      \"labels_url\": \"https://api.github.com/repos/google/material-design-icons/labels{/name}\",\n" +
            "      \"releases_url\": \"https://api.github.com/repos/google/material-design-icons/releases{/id}\",\n" +
            "      \"deployments_url\": \"https://api.github.com/repos/google/material-design-icons/deployments\",\n" +
            "      \"created_at\": \"2014-10-08T18:01:28Z\",\n" +
            "      \"updated_at\": \"2018-08-09T13:30:48Z\",\n" +
            "      \"pushed_at\": \"2018-07-21T20:52:09Z\",\n" +
            "      \"git_url\": \"git://github.com/google/material-design-icons.git\",\n" +
            "      \"ssh_url\": \"git@github.com:google/material-design-icons.git\",\n" +
            "      \"clone_url\": \"https://github.com/google/material-design-icons.git\",\n" +
            "      \"svn_url\": \"https://github.com/google/material-design-icons\",\n" +
            "      \"homepage\": \"http://google.github.io/material-design-icons/\",\n" +
            "      \"size\": 47085,\n" +
            "      \"stargazers_count\": 35632,\n" +
            "      \"watchers_count\": 35632,\n" +
            "      \"language\": \"CSS\",\n" +
            "      \"has_issues\": true,\n" +
            "      \"has_projects\": true,\n" +
            "      \"has_downloads\": false,\n" +
            "      \"has_wiki\": true,\n" +
            "      \"has_pages\": true,\n" +
            "      \"forks_count\": 7088,\n" +
            "      \"mirror_url\": null,\n" +
            "      \"archived\": false,\n" +
            "      \"open_issues_count\": 484,\n" +
            "      \"license\": {\n" +
            "        \"key\": \"apache-2.0\",\n" +
            "        \"name\": \"Apache License 2.0\",\n" +
            "        \"spdx_id\": \"Apache-2.0\",\n" +
            "        \"url\": \"https://api.github.com/licenses/apache-2.0\",\n" +
            "        \"node_id\": \"MDc6TGljZW5zZTI=\"\n" +
            "      },\n" +
            "      \"forks\": 7088,\n" +
            "      \"open_issues\": 484,\n" +
            "      \"watchers\": 35632,\n" +
            "      \"default_branch\": \"master\",\n" +
            "      \"score\": 39.209354\n" +
            "    },\n" +
            "    {\n" +
            "      \"id\": 31792824,\n" +
            "      \"node_id\": \"MDEwOlJlcG9zaXRvcnkzMTc5MjgyNA==\",\n" +
            "      \"name\": \"flutter\",\n" +
            "      \"full_name\": \"flutter/flutter\",\n" +
            "      \"owner\": {\n" +
            "        \"login\": \"flutter\",\n" +
            "        \"id\": 14101776,\n" +
            "        \"node_id\": \"MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2\",\n" +
            "        \"avatar_url\": \"https://avatars3.githubusercontent.com/u/14101776?v=4\",\n" +
            "        \"gravatar_id\": \"\",\n" +
            "        \"url\": \"https://api.github.com/users/flutter\",\n" +
            "        \"html_url\": \"https://github.com/flutter\",\n" +
            "        \"followers_url\": \"https://api.github.com/users/flutter/followers\",\n" +
            "        \"following_url\": \"https://api.github.com/users/flutter/following{/other_user}\",\n" +
            "        \"gists_url\": \"https://api.github.com/users/flutter/gists{/gist_id}\",\n" +
            "        \"starred_url\": \"https://api.github.com/users/flutter/starred{/owner}{/repo}\",\n" +
            "        \"subscriptions_url\": \"https://api.github.com/users/flutter/subscriptions\",\n" +
            "        \"organizations_url\": \"https://api.github.com/users/flutter/orgs\",\n" +
            "        \"repos_url\": \"https://api.github.com/users/flutter/repos\",\n" +
            "        \"events_url\": \"https://api.github.com/users/flutter/events{/privacy}\",\n" +
            "        \"received_events_url\": \"https://api.github.com/users/flutter/received_events\",\n" +
            "        \"type\": \"Organization\",\n" +
            "        \"site_admin\": false\n" +
            "      },\n" +
            "      \"private\": false,\n" +
            "      \"html_url\": \"https://github.com/flutter/flutter\",\n" +
            "      \"description\": \"Flutter makes it easy and fast to build beautiful mobile apps.\",\n" +
            "      \"fork\": false,\n" +
            "      \"url\": \"https://api.github.com/repos/flutter/flutter\",\n" +
            "      \"forks_url\": \"https://api.github.com/repos/flutter/flutter/forks\",\n" +
            "      \"keys_url\": \"https://api.github.com/repos/flutter/flutter/keys{/key_id}\",\n" +
            "      \"collaborators_url\": \"https://api.github.com/repos/flutter/flutter/collaborators{/collaborator}\",\n" +
            "      \"teams_url\": \"https://api.github.com/repos/flutter/flutter/teams\",\n" +
            "      \"hooks_url\": \"https://api.github.com/repos/flutter/flutter/hooks\",\n" +
            "      \"issue_events_url\": \"https://api.github.com/repos/flutter/flutter/issues/events{/number}\",\n" +
            "      \"events_url\": \"https://api.github.com/repos/flutter/flutter/events\",\n" +
            "      \"assignees_url\": \"https://api.github.com/repos/flutter/flutter/assignees{/user}\",\n" +
            "      \"branches_url\": \"https://api.github.com/repos/flutter/flutter/branches{/branch}\",\n" +
            "      \"tags_url\": \"https://api.github.com/repos/flutter/flutter/tags\",\n" +
            "      \"blobs_url\": \"https://api.github.com/repos/flutter/flutter/git/blobs{/sha}\",\n" +
            "      \"git_tags_url\": \"https://api.github.com/repos/flutter/flutter/git/tags{/sha}\",\n" +
            "      \"git_refs_url\": \"https://api.github.com/repos/flutter/flutter/git/refs{/sha}\",\n" +
            "      \"trees_url\": \"https://api.github.com/repos/flutter/flutter/git/trees{/sha}\",\n" +
            "      \"statuses_url\": \"https://api.github.com/repos/flutter/flutter/statuses/{sha}\",\n" +
            "      \"languages_url\": \"https://api.github.com/repos/flutter/flutter/languages\",\n" +
            "      \"stargazers_url\": \"https://api.github.com/repos/flutter/flutter/stargazers\",\n" +
            "      \"contributors_url\": \"https://api.github.com/repos/flutter/flutter/contributors\",\n" +
            "      \"subscribers_url\": \"https://api.github.com/repos/flutter/flutter/subscribers\",\n" +
            "      \"subscription_url\": \"https://api.github.com/repos/flutter/flutter/subscription\",\n" +
            "      \"commits_url\": \"https://api.github.com/repos/flutter/flutter/commits{/sha}\",\n" +
            "      \"git_commits_url\": \"https://api.github.com/repos/flutter/flutter/git/commits{/sha}\",\n" +
            "      \"comments_url\": \"https://api.github.com/repos/flutter/flutter/comments{/number}\",\n" +
            "      \"issue_comment_url\": \"https://api.github.com/repos/flutter/flutter/issues/comments{/number}\",\n" +
            "      \"contents_url\": \"https://api.github.com/repos/flutter/flutter/contents/{+path}\",\n" +
            "      \"compare_url\": \"https://api.github.com/repos/flutter/flutter/compare/{base}...{head}\",\n" +
            "      \"merges_url\": \"https://api.github.com/repos/flutter/flutter/merges\",\n" +
            "      \"archive_url\": \"https://api.github.com/repos/flutter/flutter/{archive_format}{/ref}\",\n" +
            "      \"downloads_url\": \"https://api.github.com/repos/flutter/flutter/downloads\",\n" +
            "      \"issues_url\": \"https://api.github.com/repos/flutter/flutter/issues{/number}\",\n" +
            "      \"pulls_url\": \"https://api.github.com/repos/flutter/flutter/pulls{/number}\",\n" +
            "      \"milestones_url\": \"https://api.github.com/repos/flutter/flutter/milestones{/number}\",\n" +
            "      \"notifications_url\": \"https://api.github.com/repos/flutter/flutter/notifications{?since,all,participating}\",\n" +
            "      \"labels_url\": \"https://api.github.com/repos/flutter/flutter/labels{/name}\",\n" +
            "      \"releases_url\": \"https://api.github.com/repos/flutter/flutter/releases{/id}\",\n" +
            "      \"deployments_url\": \"https://api.github.com/repos/flutter/flutter/deployments\",\n" +
            "      \"created_at\": \"2015-03-06T22:54:58Z\",\n" +
            "      \"updated_at\": \"2018-08-09T14:50:53Z\",\n" +
            "      \"pushed_at\": \"2018-08-09T14:12:46Z\",\n" +
            "      \"git_url\": \"git://github.com/flutter/flutter.git\",\n" +
            "      \"ssh_url\": \"git@github.com:flutter/flutter.git\",\n" +
            "      \"clone_url\": \"https://github.com/flutter/flutter.git\",\n" +
            "      \"svn_url\": \"https://github.com/flutter/flutter\",\n" +
            "      \"homepage\": \"https://flutter.io\",\n" +
            "      \"size\": 43934,\n" +
            "      \"stargazers_count\": 34750,\n" +
            "      \"watchers_count\": 34750,\n" +
            "      \"language\": \"Dart\",\n" +
            "      \"has_issues\": true,\n" +
            "      \"has_projects\": true,\n" +
            "      \"has_downloads\": true,\n" +
            "      \"has_wiki\": true,\n" +
            "      \"has_pages\": false,\n" +
            "      \"forks_count\": 3198,\n" +
            "      \"mirror_url\": null,\n" +
            "      \"archived\": false,\n" +
            "      \"open_issues_count\": 3733,\n" +
            "      \"license\": {\n" +
            "        \"key\": \"other\",\n" +
            "        \"name\": \"Other\",\n" +
            "        \"spdx_id\": null,\n" +
            "        \"url\": null,\n" +
            "        \"node_id\": \"MDc6TGljZW5zZTA=\"\n" +
            "      },\n" +
            "      \"forks\": 3198,\n" +
            "      \"open_issues\": 3733,\n" +
            "      \"watchers\": 34750,\n" +
            "      \"default_branch\": \"master\",\n" +
            "      \"score\": 42.956955\n" +
            "    },\n" +
            "    {\n" +
            "      \"id\": 28428729,\n" +
            "      \"node_id\": \"MDEwOlJlcG9zaXRvcnkyODQyODcyOQ==\",\n" +
            "      \"name\": \"awesome-android-ui\",\n" +
            "      \"full_name\": \"wasabeef/awesome-android-ui\",\n" +
            "      \"owner\": {\n" +
            "        \"login\": \"wasabeef\",\n" +
            "        \"id\": 1833474,\n" +
            "        \"node_id\": \"MDQ6VXNlcjE4MzM0NzQ=\",\n" +
            "        \"avatar_url\": \"https://avatars2.githubusercontent.com/u/1833474?v=4\",\n" +
            "        \"gravatar_id\": \"\",\n" +
            "        \"url\": \"https://api.github.com/users/wasabeef\",\n" +
            "        \"html_url\": \"https://github.com/wasabeef\",\n" +
            "        \"followers_url\": \"https://api.github.com/users/wasabeef/followers\",\n" +
            "        \"following_url\": \"https://api.github.com/users/wasabeef/following{/other_user}\",\n" +
            "        \"gists_url\": \"https://api.github.com/users/wasabeef/gists{/gist_id}\",\n" +
            "        \"starred_url\": \"https://api.github.com/users/wasabeef/starred{/owner}{/repo}\",\n" +
            "        \"subscriptions_url\": \"https://api.github.com/users/wasabeef/subscriptions\",\n" +
            "        \"organizations_url\": \"https://api.github.com/users/wasabeef/orgs\",\n" +
            "        \"repos_url\": \"https://api.github.com/users/wasabeef/repos\",\n" +
            "        \"events_url\": \"https://api.github.com/users/wasabeef/events{/privacy}\",\n" +
            "        \"received_events_url\": \"https://api.github.com/users/wasabeef/received_events\",\n" +
            "        \"type\": \"User\",\n" +
            "        \"site_admin\": false\n" +
            "      },\n" +
            "      \"private\": false,\n" +
            "      \"html_url\": \"https://github.com/wasabeef/awesome-android-ui\",\n" +
            "      \"description\": \"A curated list of awesome Android UI/UX libraries\",\n" +
            "      \"fork\": false,\n" +
            "      \"url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui\",\n" +
            "      \"forks_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/forks\",\n" +
            "      \"keys_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/keys{/key_id}\",\n" +
            "      \"collaborators_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/collaborators{/collaborator}\",\n" +
            "      \"teams_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/teams\",\n" +
            "      \"hooks_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/hooks\",\n" +
            "      \"issue_events_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/issues/events{/number}\",\n" +
            "      \"events_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/events\",\n" +
            "      \"assignees_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/assignees{/user}\",\n" +
            "      \"branches_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/branches{/branch}\",\n" +
            "      \"tags_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/tags\",\n" +
            "      \"blobs_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/git/blobs{/sha}\",\n" +
            "      \"git_tags_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/git/tags{/sha}\",\n" +
            "      \"git_refs_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/git/refs{/sha}\",\n" +
            "      \"trees_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/git/trees{/sha}\",\n" +
            "      \"statuses_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/statuses/{sha}\",\n" +
            "      \"languages_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/languages\",\n" +
            "      \"stargazers_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/stargazers\",\n" +
            "      \"contributors_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/contributors\",\n" +
            "      \"subscribers_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/subscribers\",\n" +
            "      \"subscription_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/subscription\",\n" +
            "      \"commits_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/commits{/sha}\",\n" +
            "      \"git_commits_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/git/commits{/sha}\",\n" +
            "      \"comments_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/comments{/number}\",\n" +
            "      \"issue_comment_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/issues/comments{/number}\",\n" +
            "      \"contents_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/contents/{+path}\",\n" +
            "      \"compare_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/compare/{base}...{head}\",\n" +
            "      \"merges_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/merges\",\n" +
            "      \"archive_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/{archive_format}{/ref}\",\n" +
            "      \"downloads_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/downloads\",\n" +
            "      \"issues_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/issues{/number}\",\n" +
            "      \"pulls_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/pulls{/number}\",\n" +
            "      \"milestones_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/milestones{/number}\",\n" +
            "      \"notifications_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/notifications{?since,all,participating}\",\n" +
            "      \"labels_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/labels{/name}\",\n" +
            "      \"releases_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/releases{/id}\",\n" +
            "      \"deployments_url\": \"https://api.github.com/repos/wasabeef/awesome-android-ui/deployments\",\n" +
            "      \"created_at\": \"2014-12-24T01:45:03Z\",\n" +
            "      \"updated_at\": \"2018-08-09T13:04:01Z\",\n" +
            "      \"pushed_at\": \"2018-07-30T03:16:04Z\",\n" +
            "      \"git_url\": \"git://github.com/wasabeef/awesome-android-ui.git\",\n" +
            "      \"ssh_url\": \"git@github.com:wasabeef/awesome-android-ui.git\",\n" +
            "      \"clone_url\": \"https://github.com/wasabeef/awesome-android-ui.git\",\n" +
            "      \"svn_url\": \"https://github.com/wasabeef/awesome-android-ui\",\n" +
            "      \"homepage\": \"https://twitter.com/wasabeef_jp\",\n" +
            "      \"size\": 775829,\n" +
            "      \"stargazers_count\": 31368,\n" +
            "      \"watchers_count\": 31368,\n" +
            "      \"language\": null,\n" +
            "      \"has_issues\": false,\n" +
            "      \"has_projects\": false,\n" +
            "      \"has_downloads\": true,\n" +
            "      \"has_wiki\": false,\n" +
            "      \"has_pages\": false,\n" +
            "      \"forks_count\": 8364,\n" +
            "      \"mirror_url\": null,\n" +
            "      \"archived\": false,\n" +
            "      \"open_issues_count\": 13,\n" +
            "      \"license\": null,\n" +
            "      \"forks\": 8364,\n" +
            "      \"open_issues\": 13,\n" +
            "      \"watchers\": 31368,\n" +
            "      \"default_branch\": \"master\",\n" +
            "      \"score\": 69.207\n" +
            "    },\n" +
            "    {\n" +
            "      \"id\": 892275,\n" +
            "      \"node_id\": \"MDEwOlJlcG9zaXRvcnk4OTIyNzU=\",\n" +
            "      \"name\": \"retrofit\",\n" +
            "      \"full_name\": \"square/retrofit\",\n" +
            "      \"owner\": {\n" +
            "        \"login\": \"square\",\n" +
            "        \"id\": 82592,\n" +
            "        \"node_id\": \"MDEyOk9yZ2FuaXphdGlvbjgyNTky\",\n" +
            "        \"avatar_url\": \"https://avatars0.githubusercontent.com/u/82592?v=4\",\n" +
            "        \"gravatar_id\": \"\",\n" +
            "        \"url\": \"https://api.github.com/users/square\",\n" +
            "        \"html_url\": \"https://github.com/square\",\n" +
            "        \"followers_url\": \"https://api.github.com/users/square/followers\",\n" +
            "        \"following_url\": \"https://api.github.com/users/square/following{/other_user}\",\n" +
            "        \"gists_url\": \"https://api.github.com/users/square/gists{/gist_id}\",\n" +
            "        \"starred_url\": \"https://api.github.com/users/square/starred{/owner}{/repo}\",\n" +
            "        \"subscriptions_url\": \"https://api.github.com/users/square/subscriptions\",\n" +
            "        \"organizations_url\": \"https://api.github.com/users/square/orgs\",\n" +
            "        \"repos_url\": \"https://api.github.com/users/square/repos\",\n" +
            "        \"events_url\": \"https://api.github.com/users/square/events{/privacy}\",\n" +
            "        \"received_events_url\": \"https://api.github.com/users/square/received_events\",\n" +
            "        \"type\": \"Organization\",\n" +
            "        \"site_admin\": false\n" +
            "      },\n" +
            "      \"private\": false,\n" +
            "      \"html_url\": \"https://github.com/square/retrofit\",\n" +
            "      \"description\": \"Type-safe HTTP client for Android and Java by Square, Inc.\",\n" +
            "      \"fork\": false,\n" +
            "      \"url\": \"https://api.github.com/repos/square/retrofit\",\n" +
            "      \"forks_url\": \"https://api.github.com/repos/square/retrofit/forks\",\n" +
            "      \"keys_url\": \"https://api.github.com/repos/square/retrofit/keys{/key_id}\",\n" +
            "      \"collaborators_url\": \"https://api.github.com/repos/square/retrofit/collaborators{/collaborator}\",\n" +
            "      \"teams_url\": \"https://api.github.com/repos/square/retrofit/teams\",\n" +
            "      \"hooks_url\": \"https://api.github.com/repos/square/retrofit/hooks\",\n" +
            "      \"issue_events_url\": \"https://api.github.com/repos/square/retrofit/issues/events{/number}\",\n" +
            "      \"events_url\": \"https://api.github.com/repos/square/retrofit/events\",\n" +
            "      \"assignees_url\": \"https://api.github.com/repos/square/retrofit/assignees{/user}\",\n" +
            "      \"branches_url\": \"https://api.github.com/repos/square/retrofit/branches{/branch}\",\n" +
            "      \"tags_url\": \"https://api.github.com/repos/square/retrofit/tags\",\n" +
            "      \"blobs_url\": \"https://api.github.com/repos/square/retrofit/git/blobs{/sha}\",\n" +
            "      \"git_tags_url\": \"https://api.github.com/repos/square/retrofit/git/tags{/sha}\",\n" +
            "      \"git_refs_url\": \"https://api.github.com/repos/square/retrofit/git/refs{/sha}\",\n" +
            "      \"trees_url\": \"https://api.github.com/repos/square/retrofit/git/trees{/sha}\",\n" +
            "      \"statuses_url\": \"https://api.github.com/repos/square/retrofit/statuses/{sha}\",\n" +
            "      \"languages_url\": \"https://api.github.com/repos/square/retrofit/languages\",\n" +
            "      \"stargazers_url\": \"https://api.github.com/repos/square/retrofit/stargazers\",\n" +
            "      \"contributors_url\": \"https://api.github.com/repos/square/retrofit/contributors\",\n" +
            "      \"subscribers_url\": \"https://api.github.com/repos/square/retrofit/subscribers\",\n" +
            "      \"subscription_url\": \"https://api.github.com/repos/square/retrofit/subscription\",\n" +
            "      \"commits_url\": \"https://api.github.com/repos/square/retrofit/commits{/sha}\",\n" +
            "      \"git_commits_url\": \"https://api.github.com/repos/square/retrofit/git/commits{/sha}\",\n" +
            "      \"comments_url\": \"https://api.github.com/repos/square/retrofit/comments{/number}\",\n" +
            "      \"issue_comment_url\": \"https://api.github.com/repos/square/retrofit/issues/comments{/number}\",\n" +
            "      \"contents_url\": \"https://api.github.com/repos/square/retrofit/contents/{+path}\",\n" +
            "      \"compare_url\": \"https://api.github.com/repos/square/retrofit/compare/{base}...{head}\",\n" +
            "      \"merges_url\": \"https://api.github.com/repos/square/retrofit/merges\",\n" +
            "      \"archive_url\": \"https://api.github.com/repos/square/retrofit/{archive_format}{/ref}\",\n" +
            "      \"downloads_url\": \"https://api.github.com/repos/square/retrofit/downloads\",\n" +
            "      \"issues_url\": \"https://api.github.com/repos/square/retrofit/issues{/number}\",\n" +
            "      \"pulls_url\": \"https://api.github.com/repos/square/retrofit/pulls{/number}\",\n" +
            "      \"milestones_url\": \"https://api.github.com/repos/square/retrofit/milestones{/number}\",\n" +
            "      \"notifications_url\": \"https://api.github.com/repos/square/retrofit/notifications{?since,all,participating}\",\n" +
            "      \"labels_url\": \"https://api.github.com/repos/square/retrofit/labels{/name}\",\n" +
            "      \"releases_url\": \"https://api.github.com/repos/square/retrofit/releases{/id}\",\n" +
            "      \"deployments_url\": \"https://api.github.com/repos/square/retrofit/deployments\",\n" +
            "      \"created_at\": \"2010-09-06T21:39:43Z\",\n" +
            "      \"updated_at\": \"2018-08-09T14:45:26Z\",\n" +
            "      \"pushed_at\": \"2018-07-28T21:19:29Z\",\n" +
            "      \"git_url\": \"git://github.com/square/retrofit.git\",\n" +
            "      \"ssh_url\": \"git@github.com:square/retrofit.git\",\n" +
            "      \"clone_url\": \"https://github.com/square/retrofit.git\",\n" +
            "      \"svn_url\": \"https://github.com/square/retrofit\",\n" +
            "      \"homepage\": \"http://square.github.io/retrofit/\",\n" +
            "      \"size\": 4700,\n" +
            "      \"stargazers_count\": 29050,\n" +
            "      \"watchers_count\": 29050,\n" +
            "      \"language\": \"Java\",\n" +
            "      \"has_issues\": true,\n" +
            "      \"has_projects\": false,\n" +
            "      \"has_downloads\": true,\n" +
            "      \"has_wiki\": true,\n" +
            "      \"has_pages\": true,\n" +
            "      \"forks_count\": 5597,\n" +
            "      \"mirror_url\": null,\n" +
            "      \"archived\": false,\n" +
            "      \"open_issues_count\": 64,\n" +
            "      \"license\": {\n" +
            "        \"key\": \"apache-2.0\",\n" +
            "        \"name\": \"Apache License 2.0\",\n" +
            "        \"spdx_id\": \"Apache-2.0\",\n" +
            "        \"url\": \"https://api.github.com/licenses/apache-2.0\",\n" +
            "        \"node_id\": \"MDc6TGljZW5zZTI=\"\n" +
            "      },\n" +
            "      \"forks\": 5597,\n" +
            "      \"open_issues\": 64,\n" +
            "      \"watchers\": 29050,\n" +
            "      \"default_branch\": \"master\",\n" +
            "      \"score\": 39.93163\n" +
            "    },\n" +
            "    {\n" +
            "      \"id\": 51148780,\n" +
            "      \"node_id\": \"MDEwOlJlcG9zaXRvcnk1MTE0ODc4MA==\",\n" +
            "      \"name\": \"android-architecture\",\n" +
            "      \"full_name\": \"googlesamples/android-architecture\",\n" +
            "      \"owner\": {\n" +
            "        \"login\": \"googlesamples\",\n" +
            "        \"id\": 7378196,\n" +
            "        \"node_id\": \"MDEyOk9yZ2FuaXphdGlvbjczNzgxOTY=\",\n" +
            "        \"avatar_url\": \"https://avatars3.githubusercontent.com/u/7378196?v=4\",\n" +
            "        \"gravatar_id\": \"\",\n" +
            "        \"url\": \"https://api.github.com/users/googlesamples\",\n" +
            "        \"html_url\": \"https://github.com/googlesamples\",\n" +
            "        \"followers_url\": \"https://api.github.com/users/googlesamples/followers\",\n" +
            "        \"following_url\": \"https://api.github.com/users/googlesamples/following{/other_user}\",\n" +
            "        \"gists_url\": \"https://api.github.com/users/googlesamples/gists{/gist_id}\",\n" +
            "        \"starred_url\": \"https://api.github.com/users/googlesamples/starred{/owner}{/repo}\",\n" +
            "        \"subscriptions_url\": \"https://api.github.com/users/googlesamples/subscriptions\",\n" +
            "        \"organizations_url\": \"https://api.github.com/users/googlesamples/orgs\",\n" +
            "        \"repos_url\": \"https://api.github.com/users/googlesamples/repos\",\n" +
            "        \"events_url\": \"https://api.github.com/users/googlesamples/events{/privacy}\",\n" +
            "        \"received_events_url\": \"https://api.github.com/users/googlesamples/received_events\",\n" +
            "        \"type\": \"Organization\",\n" +
            "        \"site_admin\": false\n" +
            "      },\n" +
            "      \"private\": false,\n" +
            "      \"html_url\": \"https://github.com/googlesamples/android-architecture\",\n" +
            "      \"description\": \"A collection of samples to discuss and showcase different architectural tools and patterns for Android apps.\",\n" +
            "      \"fork\": false,\n" +
            "      \"url\": \"https://api.github.com/repos/googlesamples/android-architecture\",\n" +
            "      \"forks_url\": \"https://api.github.com/repos/googlesamples/android-architecture/forks\",\n" +
            "      \"keys_url\": \"https://api.github.com/repos/googlesamples/android-architecture/keys{/key_id}\",\n" +
            "      \"collaborators_url\": \"https://api.github.com/repos/googlesamples/android-architecture/collaborators{/collaborator}\",\n" +
            "      \"teams_url\": \"https://api.github.com/repos/googlesamples/android-architecture/teams\",\n" +
            "      \"hooks_url\": \"https://api.github.com/repos/googlesamples/android-architecture/hooks\",\n" +
            "      \"issue_events_url\": \"https://api.github.com/repos/googlesamples/android-architecture/issues/events{/number}\",\n" +
            "      \"events_url\": \"https://api.github.com/repos/googlesamples/android-architecture/events\",\n" +
            "      \"assignees_url\": \"https://api.github.com/repos/googlesamples/android-architecture/assignees{/user}\",\n" +
            "      \"branches_url\": \"https://api.github.com/repos/googlesamples/android-architecture/branches{/branch}\",\n" +
            "      \"tags_url\": \"https://api.github.com/repos/googlesamples/android-architecture/tags\",\n" +
            "      \"blobs_url\": \"https://api.github.com/repos/googlesamples/android-architecture/git/blobs{/sha}\",\n" +
            "      \"git_tags_url\": \"https://api.github.com/repos/googlesamples/android-architecture/git/tags{/sha}\",\n" +
            "      \"git_refs_url\": \"https://api.github.com/repos/googlesamples/android-architecture/git/refs{/sha}\",\n" +
            "      \"trees_url\": \"https://api.github.com/repos/googlesamples/android-architecture/git/trees{/sha}\",\n" +
            "      \"statuses_url\": \"https://api.github.com/repos/googlesamples/android-architecture/statuses/{sha}\",\n" +
            "      \"languages_url\": \"https://api.github.com/repos/googlesamples/android-architecture/languages\",\n" +
            "      \"stargazers_url\": \"https://api.github.com/repos/googlesamples/android-architecture/stargazers\",\n" +
            "      \"contributors_url\": \"https://api.github.com/repos/googlesamples/android-architecture/contributors\",\n" +
            "      \"subscribers_url\": \"https://api.github.com/repos/googlesamples/android-architecture/subscribers\",\n" +
            "      \"subscription_url\": \"https://api.github.com/repos/googlesamples/android-architecture/subscription\",\n" +
            "      \"commits_url\": \"https://api.github.com/repos/googlesamples/android-architecture/commits{/sha}\",\n" +
            "      \"git_commits_url\": \"https://api.github.com/repos/googlesamples/android-architecture/git/commits{/sha}\",\n" +
            "      \"comments_url\": \"https://api.github.com/repos/googlesamples/android-architecture/comments{/number}\",\n" +
            "      \"issue_comment_url\": \"https://api.github.com/repos/googlesamples/android-architecture/issues/comments{/number}\",\n" +
            "      \"contents_url\": \"https://api.github.com/repos/googlesamples/android-architecture/contents/{+path}\",\n" +
            "      \"compare_url\": \"https://api.github.com/repos/googlesamples/android-architecture/compare/{base}...{head}\",\n" +
            "      \"merges_url\": \"https://api.github.com/repos/googlesamples/android-architecture/merges\",\n" +
            "      \"archive_url\": \"https://api.github.com/repos/googlesamples/android-architecture/{archive_format}{/ref}\",\n" +
            "      \"downloads_url\": \"https://api.github.com/repos/googlesamples/android-architecture/downloads\",\n" +
            "      \"issues_url\": \"https://api.github.com/repos/googlesamples/android-architecture/issues{/number}\",\n" +
            "      \"pulls_url\": \"https://api.github.com/repos/googlesamples/android-architecture/pulls{/number}\",\n" +
            "      \"milestones_url\": \"https://api.github.com/repos/googlesamples/android-architecture/milestones{/number}\",\n" +
            "      \"notifications_url\": \"https://api.github.com/repos/googlesamples/android-architecture/notifications{?since,all,participating}\",\n" +
            "      \"labels_url\": \"https://api.github.com/repos/googlesamples/android-architecture/labels{/name}\",\n" +
            "      \"releases_url\": \"https://api.github.com/repos/googlesamples/android-architecture/releases{/id}\",\n" +
            "      \"deployments_url\": \"https://api.github.com/repos/googlesamples/android-architecture/deployments\",\n" +
            "      \"created_at\": \"2016-02-05T13:42:07Z\",\n" +
            "      \"updated_at\": \"2018-08-09T14:30:15Z\",\n" +
            "      \"pushed_at\": \"2018-06-23T23:34:09Z\",\n" +
            "      \"git_url\": \"git://github.com/googlesamples/android-architecture.git\",\n" +
            "      \"ssh_url\": \"git@github.com:googlesamples/android-architecture.git\",\n" +
            "      \"clone_url\": \"https://github.com/googlesamples/android-architecture.git\",\n" +
            "      \"svn_url\": \"https://github.com/googlesamples/android-architecture\",\n" +
            "      \"homepage\": \"\",\n" +
            "      \"size\": 8197,\n" +
            "      \"stargazers_count\": 28763,\n" +
            "      \"watchers_count\": 28763,\n" +
            "      \"language\": null,\n" +
            "      \"has_issues\": true,\n" +
            "      \"has_projects\": true,\n" +
            "      \"has_downloads\": true,\n" +
            "      \"has_wiki\": true,\n" +
            "      \"has_pages\": false,\n" +
            "      \"forks_count\": 8116,\n" +
            "      \"mirror_url\": null,\n" +
            "      \"archived\": false,\n" +
            "      \"open_issues_count\": 110,\n" +
            "      \"license\": {\n" +
            "        \"key\": \"apache-2.0\",\n" +
            "        \"name\": \"Apache License 2.0\",\n" +
            "        \"spdx_id\": \"Apache-2.0\",\n" +
            "        \"url\": \"https://api.github.com/licenses/apache-2.0\",\n" +
            "        \"node_id\": \"MDc6TGljZW5zZTI=\"\n" +
            "      },\n" +
            "      \"forks\": 8116,\n" +
            "      \"open_issues\": 110,\n" +
            "      \"watchers\": 28763,\n" +
            "      \"default_branch\": \"master\",\n" +
            "      \"score\": 72.73293\n" +
            "    },\n" +
            "    {\n" +
            "      \"id\": 5152285,\n" +
            "      \"node_id\": \"MDEwOlJlcG9zaXRvcnk1MTUyMjg1\",\n" +
            "      \"name\": \"okhttp\",\n" +
            "      \"full_name\": \"square/okhttp\",\n" +
            "      \"owner\": {\n" +
            "        \"login\": \"square\",\n" +
            "        \"id\": 82592,\n" +
            "        \"node_id\": \"MDEyOk9yZ2FuaXphdGlvbjgyNTky\",\n" +
            "        \"avatar_url\": \"https://avatars0.githubusercontent.com/u/82592?v=4\",\n" +
            "        \"gravatar_id\": \"\",\n" +
            "        \"url\": \"https://api.github.com/users/square\",\n" +
            "        \"html_url\": \"https://github.com/square\",\n" +
            "        \"followers_url\": \"https://api.github.com/users/square/followers\",\n" +
            "        \"following_url\": \"https://api.github.com/users/square/following{/other_user}\",\n" +
            "        \"gists_url\": \"https://api.github.com/users/square/gists{/gist_id}\",\n" +
            "        \"starred_url\": \"https://api.github.com/users/square/starred{/owner}{/repo}\",\n" +
            "        \"subscriptions_url\": \"https://api.github.com/users/square/subscriptions\",\n" +
            "        \"organizations_url\": \"https://api.github.com/users/square/orgs\",\n" +
            "        \"repos_url\": \"https://api.github.com/users/square/repos\",\n" +
            "        \"events_url\": \"https://api.github.com/users/square/events{/privacy}\",\n" +
            "        \"received_events_url\": \"https://api.github.com/users/square/received_events\",\n" +
            "        \"type\": \"Organization\",\n" +
            "        \"site_admin\": false\n" +
            "      },\n" +
            "      \"private\": false,\n" +
            "      \"html_url\": \"https://github.com/square/okhttp\",\n" +
            "      \"description\": \"An HTTP+HTTP/2 client for Android and Java applications.\",\n" +
            "      \"fork\": false,\n" +
            "      \"url\": \"https://api.github.com/repos/square/okhttp\",\n" +
            "      \"forks_url\": \"https://api.github.com/repos/square/okhttp/forks\",\n" +
            "      \"keys_url\": \"https://api.github.com/repos/square/okhttp/keys{/key_id}\",\n" +
            "      \"collaborators_url\": \"https://api.github.com/repos/square/okhttp/collaborators{/collaborator}\",\n" +
            "      \"teams_url\": \"https://api.github.com/repos/square/okhttp/teams\",\n" +
            "      \"hooks_url\": \"https://api.github.com/repos/square/okhttp/hooks\",\n" +
            "      \"issue_events_url\": \"https://api.github.com/repos/square/okhttp/issues/events{/number}\",\n" +
            "      \"events_url\": \"https://api.github.com/repos/square/okhttp/events\",\n" +
            "      \"assignees_url\": \"https://api.github.com/repos/square/okhttp/assignees{/user}\",\n" +
            "      \"branches_url\": \"https://api.github.com/repos/square/okhttp/branches{/branch}\",\n" +
            "      \"tags_url\": \"https://api.github.com/repos/square/okhttp/tags\",\n" +
            "      \"blobs_url\": \"https://api.github.com/repos/square/okhttp/git/blobs{/sha}\",\n" +
            "      \"git_tags_url\": \"https://api.github.com/repos/square/okhttp/git/tags{/sha}\",\n" +
            "      \"git_refs_url\": \"https://api.github.com/repos/square/okhttp/git/refs{/sha}\",\n" +
            "      \"trees_url\": \"https://api.github.com/repos/square/okhttp/git/trees{/sha}\",\n" +
            "      \"statuses_url\": \"https://api.github.com/repos/square/okhttp/statuses/{sha}\",\n" +
            "      \"languages_url\": \"https://api.github.com/repos/square/okhttp/languages\",\n" +
            "      \"stargazers_url\": \"https://api.github.com/repos/square/okhttp/stargazers\",\n" +
            "      \"contributors_url\": \"https://api.github.com/repos/square/okhttp/contributors\",\n" +
            "      \"subscribers_url\": \"https://api.github.com/repos/square/okhttp/subscribers\",\n" +
            "      \"subscription_url\": \"https://api.github.com/repos/square/okhttp/subscription\",\n" +
            "      \"commits_url\": \"https://api.github.com/repos/square/okhttp/commits{/sha}\",\n" +
            "      \"git_commits_url\": \"https://api.github.com/repos/square/okhttp/git/commits{/sha}\",\n" +
            "      \"comments_url\": \"https://api.github.com/repos/square/okhttp/comments{/number}\",\n" +
            "      \"issue_comment_url\": \"https://api.github.com/repos/square/okhttp/issues/comments{/number}\",\n" +
            "      \"contents_url\": \"https://api.github.com/repos/square/okhttp/contents/{+path}\",\n" +
            "      \"compare_url\": \"https://api.github.com/repos/square/okhttp/compare/{base}...{head}\",\n" +
            "      \"merges_url\": \"https://api.github.com/repos/square/okhttp/merges\",\n" +
            "      \"archive_url\": \"https://api.github.com/repos/square/okhttp/{archive_format}{/ref}\",\n" +
            "      \"downloads_url\": \"https://api.github.com/repos/square/okhttp/downloads\",\n" +
            "      \"issues_url\": \"https://api.github.com/repos/square/okhttp/issues{/number}\",\n" +
            "      \"pulls_url\": \"https://api.github.com/repos/square/okhttp/pulls{/number}\",\n" +
            "      \"milestones_url\": \"https://api.github.com/repos/square/okhttp/milestones{/number}\",\n" +
            "      \"notifications_url\": \"https://api.github.com/repos/square/okhttp/notifications{?since,all,participating}\",\n" +
            "      \"labels_url\": \"https://api.github.com/repos/square/okhttp/labels{/name}\",\n" +
            "      \"releases_url\": \"https://api.github.com/repos/square/okhttp/releases{/id}\",\n" +
            "      \"deployments_url\": \"https://api.github.com/repos/square/okhttp/deployments\",\n" +
            "      \"created_at\": \"2012-07-23T13:42:55Z\",\n" +
            "      \"updated_at\": \"2018-08-09T13:37:29Z\",\n" +
            "      \"pushed_at\": \"2018-08-09T08:06:08Z\",\n" +
            "      \"git_url\": \"git://github.com/square/okhttp.git\",\n" +
            "      \"ssh_url\": \"git@github.com:square/okhttp.git\",\n" +
            "      \"clone_url\": \"https://github.com/square/okhttp.git\",\n" +
            "      \"svn_url\": \"https://github.com/square/okhttp\",\n" +
            "      \"homepage\": \"http://square.github.io/okhttp/\",\n" +
            "      \"size\": 17962,\n" +
            "      \"stargazers_count\": 28043,\n" +
            "      \"watchers_count\": 28043,\n" +
            "      \"language\": \"Java\",\n" +
            "      \"has_issues\": true,\n" +
            "      \"has_projects\": false,\n" +
            "      \"has_downloads\": true,\n" +
            "      \"has_wiki\": true,\n" +
            "      \"has_pages\": true,\n" +
            "      \"forks_count\": 6471,\n" +
            "      \"mirror_url\": null,\n" +
            "      \"archived\": false,\n" +
            "      \"open_issues_count\": 152,\n" +
            "      \"license\": {\n" +
            "        \"key\": \"apache-2.0\",\n" +
            "        \"name\": \"Apache License 2.0\",\n" +
            "        \"spdx_id\": \"Apache-2.0\",\n" +
            "        \"url\": \"https://api.github.com/licenses/apache-2.0\",\n" +
            "        \"node_id\": \"MDc6TGljZW5zZTI=\"\n" +
            "      },\n" +
            "      \"forks\": 6471,\n" +
            "      \"open_issues\": 152,\n" +
            "      \"watchers\": 28043,\n" +
            "      \"default_branch\": \"master\",\n" +
            "      \"score\": 49.224438\n" +
            "    },\n" +
            "    {\n" +
            "      \"id\": 15653276,\n" +
            "      \"node_id\": \"MDEwOlJlcG9zaXRvcnkxNTY1MzI3Ng==\",\n" +
            "      \"name\": \"android-open-project\",\n" +
            "      \"full_name\": \"Trinea/android-open-project\",\n" +
            "      \"owner\": {\n" +
            "        \"login\": \"Trinea\",\n" +
            "        \"id\": 1169522,\n" +
            "        \"node_id\": \"MDQ6VXNlcjExNjk1MjI=\",\n" +
            "        \"avatar_url\": \"https://avatars0.githubusercontent.com/u/1169522?v=4\",\n" +
            "        \"gravatar_id\": \"\",\n" +
            "        \"url\": \"https://api.github.com/users/Trinea\",\n" +
            "        \"html_url\": \"https://github.com/Trinea\",\n" +
            "        \"followers_url\": \"https://api.github.com/users/Trinea/followers\",\n" +
            "        \"following_url\": \"https://api.github.com/users/Trinea/following{/other_user}\",\n" +
            "        \"gists_url\": \"https://api.github.com/users/Trinea/gists{/gist_id}\",\n" +
            "        \"starred_url\": \"https://api.github.com/users/Trinea/starred{/owner}{/repo}\",\n" +
            "        \"subscriptions_url\": \"https://api.github.com/users/Trinea/subscriptions\",\n" +
            "        \"organizations_url\": \"https://api.github.com/users/Trinea/orgs\",\n" +
            "        \"repos_url\": \"https://api.github.com/users/Trinea/repos\",\n" +
            "        \"events_url\": \"https://api.github.com/users/Trinea/events{/privacy}\",\n" +
            "        \"received_events_url\": \"https://api.github.com/users/Trinea/received_events\",\n" +
            "        \"type\": \"User\",\n" +
            "        \"site_admin\": false\n" +
            "      },\n" +
            "      \"private\": false,\n" +
            "      \"html_url\": \"https://github.com/Trinea/android-open-project\",\n" +
            "      \"description\": \"A categorized collection of Android Open Source Projects,  More powerful web version:\",\n" +
            "      \"fork\": false,\n" +
            "      \"url\": \"https://api.github.com/repos/Trinea/android-open-project\",\n" +
            "      \"forks_url\": \"https://api.github.com/repos/Trinea/android-open-project/forks\",\n" +
            "      \"keys_url\": \"https://api.github.com/repos/Trinea/android-open-project/keys{/key_id}\",\n" +
            "      \"collaborators_url\": \"https://api.github.com/repos/Trinea/android-open-project/collaborators{/collaborator}\",\n" +
            "      \"teams_url\": \"https://api.github.com/repos/Trinea/android-open-project/teams\",\n" +
            "      \"hooks_url\": \"https://api.github.com/repos/Trinea/android-open-project/hooks\",\n" +
            "      \"issue_events_url\": \"https://api.github.com/repos/Trinea/android-open-project/issues/events{/number}\",\n" +
            "      \"events_url\": \"https://api.github.com/repos/Trinea/android-open-project/events\",\n" +
            "      \"assignees_url\": \"https://api.github.com/repos/Trinea/android-open-project/assignees{/user}\",\n" +
            "      \"branches_url\": \"https://api.github.com/repos/Trinea/android-open-project/branches{/branch}\",\n" +
            "      \"tags_url\": \"https://api.github.com/repos/Trinea/android-open-project/tags\",\n" +
            "      \"blobs_url\": \"https://api.github.com/repos/Trinea/android-open-project/git/blobs{/sha}\",\n" +
            "      \"git_tags_url\": \"https://api.github.com/repos/Trinea/android-open-project/git/tags{/sha}\",\n" +
            "      \"git_refs_url\": \"https://api.github.com/repos/Trinea/android-open-project/git/refs{/sha}\",\n" +
            "      \"trees_url\": \"https://api.github.com/repos/Trinea/android-open-project/git/trees{/sha}\",\n" +
            "      \"statuses_url\": \"https://api.github.com/repos/Trinea/android-open-project/statuses/{sha}\",\n" +
            "      \"languages_url\": \"https://api.github.com/repos/Trinea/android-open-project/languages\",\n" +
            "      \"stargazers_url\": \"https://api.github.com/repos/Trinea/android-open-project/stargazers\",\n" +
            "      \"contributors_url\": \"https://api.github.com/repos/Trinea/android-open-project/contributors\",\n" +
            "      \"subscribers_url\": \"https://api.github.com/repos/Trinea/android-open-project/subscribers\",\n" +
            "      \"subscription_url\": \"https://api.github.com/repos/Trinea/android-open-project/subscription\",\n" +
            "      \"commits_url\": \"https://api.github.com/repos/Trinea/android-open-project/commits{/sha}\",\n" +
            "      \"git_commits_url\": \"https://api.github.com/repos/Trinea/android-open-project/git/commits{/sha}\",\n" +
            "      \"comments_url\": \"https://api.github.com/repos/Trinea/android-open-project/comments{/number}\",\n" +
            "      \"issue_comment_url\": \"https://api.github.com/repos/Trinea/android-open-project/issues/comments{/number}\",\n" +
            "      \"contents_url\": \"https://api.github.com/repos/Trinea/android-open-project/contents/{+path}\",\n" +
            "      \"compare_url\": \"https://api.github.com/repos/Trinea/android-open-project/compare/{base}...{head}\",\n" +
            "      \"merges_url\": \"https://api.github.com/repos/Trinea/android-open-project/merges\",\n" +
            "      \"archive_url\": \"https://api.github.com/repos/Trinea/android-open-project/{archive_format}{/ref}\",\n" +
            "      \"downloads_url\": \"https://api.github.com/repos/Trinea/android-open-project/downloads\",\n" +
            "      \"issues_url\": \"https://api.github.com/repos/Trinea/android-open-project/issues{/number}\",\n" +
            "      \"pulls_url\": \"https://api.github.com/repos/Trinea/android-open-project/pulls{/number}\",\n" +
            "      \"milestones_url\": \"https://api.github.com/repos/Trinea/android-open-project/milestones{/number}\",\n" +
            "      \"notifications_url\": \"https://api.github.com/repos/Trinea/android-open-project/notifications{?since,all,participating}\",\n" +
            "      \"labels_url\": \"https://api.github.com/repos/Trinea/android-open-project/labels{/name}\",\n" +
            "      \"releases_url\": \"https://api.github.com/repos/Trinea/android-open-project/releases{/id}\",\n" +
            "      \"deployments_url\": \"https://api.github.com/repos/Trinea/android-open-project/deployments\",\n" +
            "      \"created_at\": \"2014-01-05T15:20:15Z\",\n" +
            "      \"updated_at\": \"2018-08-09T12:04:01Z\",\n" +
            "      \"pushed_at\": \"2018-06-10T06:13:07Z\",\n" +
            "      \"git_url\": \"git://github.com/Trinea/android-open-project.git\",\n" +
            "      \"ssh_url\": \"git@github.com:Trinea/android-open-project.git\",\n" +
            "      \"clone_url\": \"https://github.com/Trinea/android-open-project.git\",\n" +
            "      \"svn_url\": \"https://github.com/Trinea/android-open-project\",\n" +
            "      \"homepage\": \"http://codekk.com/\",\n" +
            "      \"size\": 2144,\n" +
            "      \"stargazers_count\": 27172,\n" +
            "      \"watchers_count\": 27172,\n" +
            "      \"language\": null,\n" +
            "      \"has_issues\": true,\n" +
            "      \"has_projects\": true,\n" +
            "      \"has_downloads\": true,\n" +
            "      \"has_wiki\": true,\n" +
            "      \"has_pages\": false,\n" +
            "      \"forks_count\": 11944,\n" +
            "      \"mirror_url\": null,\n" +
            "      \"archived\": false,\n" +
            "      \"open_issues_count\": 11,\n" +
            "      \"license\": {\n" +
            "        \"key\": \"apache-2.0\",\n" +
            "        \"name\": \"Apache License 2.0\",\n" +
            "        \"spdx_id\": \"Apache-2.0\",\n" +
            "        \"url\": \"https://api.github.com/licenses/apache-2.0\",\n" +
            "        \"node_id\": \"MDc6TGljZW5zZTI=\"\n" +
            "      },\n" +
            "      \"forks\": 11944,\n" +
            "      \"open_issues\": 11,\n" +
            "      \"watchers\": 27172,\n" +
            "      \"default_branch\": \"master\",\n" +
            "      \"score\": 70.691216\n" +
            "    },\n" +
            "    {\n" +
            "      \"id\": 55076063,\n" +
            "      \"node_id\": \"MDEwOlJlcG9zaXRvcnk1NTA3NjA2Mw==\",\n" +
            "      \"name\": \"Awesome-Hacking\",\n" +
            "      \"full_name\": \"Hack-with-Github/Awesome-Hacking\",\n" +
            "      \"owner\": {\n" +
            "        \"login\": \"Hack-with-Github\",\n" +
            "        \"id\": 18143746,\n" +
            "        \"node_id\": \"MDEyOk9yZ2FuaXphdGlvbjE4MTQzNzQ2\",\n" +
            "        \"avatar_url\": \"https://avatars3.githubusercontent.com/u/18143746?v=4\",\n" +
            "        \"gravatar_id\": \"\",\n" +
            "        \"url\": \"https://api.github.com/users/Hack-with-Github\",\n" +
            "        \"html_url\": \"https://github.com/Hack-with-Github\",\n" +
            "        \"followers_url\": \"https://api.github.com/users/Hack-with-Github/followers\",\n" +
            "        \"following_url\": \"https://api.github.com/users/Hack-with-Github/following{/other_user}\",\n" +
            "        \"gists_url\": \"https://api.github.com/users/Hack-with-Github/gists{/gist_id}\",\n" +
            "        \"starred_url\": \"https://api.github.com/users/Hack-with-Github/starred{/owner}{/repo}\",\n" +
            "        \"subscriptions_url\": \"https://api.github.com/users/Hack-with-Github/subscriptions\",\n" +
            "        \"organizations_url\": \"https://api.github.com/users/Hack-with-Github/orgs\",\n" +
            "        \"repos_url\": \"https://api.github.com/users/Hack-with-Github/repos\",\n" +
            "        \"events_url\": \"https://api.github.com/users/Hack-with-Github/events{/privacy}\",\n" +
            "        \"received_events_url\": \"https://api.github.com/users/Hack-with-Github/received_events\",\n" +
            "        \"type\": \"Organization\",\n" +
            "        \"site_admin\": false\n" +
            "      },\n" +
            "      \"private\": false,\n" +
            "      \"html_url\": \"https://github.com/Hack-with-Github/Awesome-Hacking\",\n" +
            "      \"description\": \"A collection of various awesome lists for hackers, pentesters and security researchers\",\n" +
            "      \"fork\": false,\n" +
            "      \"url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking\",\n" +
            "      \"forks_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/forks\",\n" +
            "      \"keys_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/keys{/key_id}\",\n" +
            "      \"collaborators_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/collaborators{/collaborator}\",\n" +
            "      \"teams_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/teams\",\n" +
            "      \"hooks_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/hooks\",\n" +
            "      \"issue_events_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/issues/events{/number}\",\n" +
            "      \"events_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/events\",\n" +
            "      \"assignees_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/assignees{/user}\",\n" +
            "      \"branches_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/branches{/branch}\",\n" +
            "      \"tags_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/tags\",\n" +
            "      \"blobs_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/git/blobs{/sha}\",\n" +
            "      \"git_tags_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/git/tags{/sha}\",\n" +
            "      \"git_refs_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/git/refs{/sha}\",\n" +
            "      \"trees_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/git/trees{/sha}\",\n" +
            "      \"statuses_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/statuses/{sha}\",\n" +
            "      \"languages_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/languages\",\n" +
            "      \"stargazers_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/stargazers\",\n" +
            "      \"contributors_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/contributors\",\n" +
            "      \"subscribers_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/subscribers\",\n" +
            "      \"subscription_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/subscription\",\n" +
            "      \"commits_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/commits{/sha}\",\n" +
            "      \"git_commits_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/git/commits{/sha}\",\n" +
            "      \"comments_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/comments{/number}\",\n" +
            "      \"issue_comment_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/issues/comments{/number}\",\n" +
            "      \"contents_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/contents/{+path}\",\n" +
            "      \"compare_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/compare/{base}...{head}\",\n" +
            "      \"merges_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/merges\",\n" +
            "      \"archive_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/{archive_format}{/ref}\",\n" +
            "      \"downloads_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/downloads\",\n" +
            "      \"issues_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/issues{/number}\",\n" +
            "      \"pulls_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/pulls{/number}\",\n" +
            "      \"milestones_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/milestones{/number}\",\n" +
            "      \"notifications_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/notifications{?since,all,participating}\",\n" +
            "      \"labels_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/labels{/name}\",\n" +
            "      \"releases_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/releases{/id}\",\n" +
            "      \"deployments_url\": \"https://api.github.com/repos/Hack-with-Github/Awesome-Hacking/deployments\",\n" +
            "      \"created_at\": \"2016-03-30T15:47:10Z\",\n" +
            "      \"updated_at\": \"2018-08-09T12:04:40Z\",\n" +
            "      \"pushed_at\": \"2018-07-08T17:08:24Z\",\n" +
            "      \"git_url\": \"git://github.com/Hack-with-Github/Awesome-Hacking.git\",\n" +
            "      \"ssh_url\": \"git@github.com:Hack-with-Github/Awesome-Hacking.git\",\n" +
            "      \"clone_url\": \"https://github.com/Hack-with-Github/Awesome-Hacking.git\",\n" +
            "      \"svn_url\": \"https://github.com/Hack-with-Github/Awesome-Hacking\",\n" +
            "      \"homepage\": null,\n" +
            "      \"size\": 144,\n" +
            "      \"stargazers_count\": 25211,\n" +
            "      \"watchers_count\": 25211,\n" +
            "      \"language\": null,\n" +
            "      \"has_issues\": true,\n" +
            "      \"has_projects\": true,\n" +
            "      \"has_downloads\": true,\n" +
            "      \"has_wiki\": true,\n" +
            "      \"has_pages\": false,\n" +
            "      \"forks_count\": 3831,\n" +
            "      \"mirror_url\": null,\n" +
            "      \"archived\": false,\n" +
            "      \"open_issues_count\": 0,\n" +
            "      \"license\": {\n" +
            "        \"key\": \"cc0-1.0\",\n" +
            "        \"name\": \"Creative Commons Zero v1.0 Universal\",\n" +
            "        \"spdx_id\": \"CC0-1.0\",\n" +
            "        \"url\": \"https://api.github.com/licenses/cc0-1.0\",\n" +
            "        \"node_id\": \"MDc6TGljZW5zZTY=\"\n" +
            "      },\n" +
            "      \"forks\": 3831,\n" +
            "      \"open_issues\": 0,\n" +
            "      \"watchers\": 25211,\n" +
            "      \"default_branch\": \"master\",\n" +
            "      \"score\": 30.295017 }]}";



}
